Campaign Classic 3.x (Swift) Update read me instruction
AdobeDocs/aep-mobile-sdkdocs pull request #122
Opened 2022-11-04 17:39 UTC by PravinPK

## Description

Update the missed out CampaignClassic 3.x install instruction from gitbook (PR)

2022-11-04 18:45 UTC, swarna04 requested changes
@PravinPK I've provided feedback here.

2022-11-04 18:45 UTC, swarna04 commented on src/pages/documentation/adobe-campaign-classic/tabs/index.md
> +   import ACPLifecycle
Remove `pod 'ACPLifecycle'` on L57 as well.

2022-11-04 18:45 UTC, swarna04 commented on src/pages/documentation/adobe-campaign-classic/tabs/index.md
>  <Variant platform="ios-aep" task="register" repeat="1"/>
Fix the `repeat` count here too.

2022-11-04 19:38 UTC, PravinPK commented on src/pages/documentation/adobe-campaign-classic/tabs/index.md
> +    MobileCore.configureWith(appId: "APP-ID")
Good point. 
But we might need to replace this in all our extensions to be uniform. Should I create a task for it ?

2022-11-08 17:58 UTC, hbhandal80 reviewed
Looks good to me :)

2022-11-22 21:30 UTC, emdobrin commented on src/pages/documentation/adobe-campaign-classic/tabs/index.md
> +<Variant platform="ios-aep" task="add" repeat="8"/>
does this tab show the objectivec example or should this be 9?

2022-11-22 22:07 UTC, merged