Add Messaging 2.0.0 release notes
AdobeDocs/aep-mobile-sdkdocs pull request #241
Opened 2023-02-22 21:27 UTC by rymorale

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-02-22 21:33 UTC, calebk1 reviewed
Couple of questions!

2023-02-22 21:33 UTC, calebk1 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +### Android AEPMessaging 2.0.0
Are we changing this to just be "Messaging 2.0.0", rather than AEPMessaging?

2023-02-22 21:33 UTC, calebk1 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +* Updates the AEPCore dependency to 2.0.1 which resolves inconsistencies between the Android and iOS MessagingDelegate classes.
"... to 2.0.1, which resolves..."

2023-02-22 21:45 UTC, praveek commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
>  ### Android AEPMessaging 2.0.1
Can we just call it Android Messaging 2.0.1?

2023-02-22 21:45 UTC, praveek commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +* Updates the AEPCore dependency to 2.0.1 which resolves inconsistencies between the Android and iOS MessagingDelegate classes.
Core dependency

2023-02-22 21:47 UTC, praveek commented
@rymorale Can you also change the base branch to staging and resolve conflicts?

2023-02-22 22:20 UTC, swarna04 requested changes

2023-02-22 22:20 UTC, swarna04 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
>  ### Android AEPMessaging 2.0.1
rename AEPMessaging -> Messaging everywhere here.

2023-02-22 22:20 UTC, swarna04 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +* Adds support for AEP 2.x extensions. Note, AEPMessaging 2.0.0 is not backwards compatible with the ACP 1.x extensions.
Major version update for [Adobe Journey Optimizer](./index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is already available as an [open source project on GitHub](https://github.com/adobe/aepsdk-messaging-android).

This release also adds the support for Adobe Journey Optimizer powered in-app messages.

2023-02-22 22:20 UTC, swarna04 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +* Adds support for AEP 2.x extensions. Note, AEPMessaging 2.0.0 is not backwards compatible with the ACP 1.x extensions.
This update will make the release note consistent with other extension release notes.

2023-02-22 22:21 UTC, swarna04 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
>  ### Android AEPMessaging 2.0.1
Sorry I didn't notice Caleb and Praveen called it out too.

2023-02-23 17:20 UTC, swarna04 approved these changes

2023-02-23 17:21 UTC, swarna04 commented on src/pages/documentation/adobe-journey-optimizer/release-notes.md
> +* Major version update for [Adobe Journey Optimizer](../adobe-journey-optimizer/index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is alrea
The link here should be ./index.md

2023-02-23 18:35 UTC, merged