Fix Places formatting
AdobeDocs/aep-mobile-sdkdocs pull request #249
Opened 2023-02-23 23:38 UTC by PravinPK

- Added release notes (subfolder and main page)
- Fix the API reference formatting issue
- Fix API header

2023-02-23 23:48 UTC, swarna04 requested changes

2023-02-23 23:48 UTC, swarna04 commented on src/pages/documentation/release-notes/index.md
> +* Major version update for [Adobe Experience Platform Location Service](../places/index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is alr
already -> now

2023-02-23 23:48 UTC, swarna04 commented on src/pages/documentation/places/release-notes.md
> +* Major version update for [Adobe Experience Platform Location Service](./index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is already ava
already -> now

2023-02-23 23:48 UTC, swarna04 commented on src/pages/documentation/places/release-notes.md
> +* Major version update for [Adobe Experience Platform Location Service](./index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is already ava
Can we also add info on the removal of an overloaded API with this release in the notes here.

2023-02-24 00:01 UTC, calebk1 approved these changes
After Swarna's changes are made, we'll be good! (Marking as approved so I don't have to re-review this a second time :p)

2023-02-25 00:27 UTC, swarna04 requested changes

2023-02-25 00:27 UTC, swarna04 commented on src/pages/documentation/release-notes/index.md
> +* Major version update for [Identity for Edge Network](../identity-for-edge-network/index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is n
These extensions - Consent, Optimize, Edge, Edge Identity etc were already open sourced with their 1.x releases so we stated so. Let's not update them.

2023-02-25 00:27 UTC, swarna04 commented on src/pages/documentation/release-notes/index.md
> +* Major version update for [Adobe Experience Platform Location Service](./index.md) for Adobe Experience Platform Mobile SDKs on Android compatible with Mobile Core 2.0.0. This library is now availab
Let's fix the link here 
`[Adobe Experience Platform Location Service](../places/index.md)`

2023-02-25 00:27 UTC, swarna04 commented on src/pages/documentation/release-notes/index.md
> +1. `getNearbyPointsOfInterest` API without the errorcallback has been removed.
Suggest rephrase:
The `getNearbyPointsOfInterest` API without the errorCallback has been removed. Alternatively, use the below overloaded API which provides both successCallback and errorCallback: 
```java
public static void getNearbyPointsOfInterest(final Location location,
			final int limit,
			final AdobeCallback<List<PlacesPOI>> successCallback,
			final AdobeCallback<PlacesRequestError> errorCallback)
```

2023-02-27 18:11 UTC, swarna04 approved these changes

2023-02-27 18:11 UTC, merged