Metadata
AdobeDocs/aep-mobile-sdkdocs pull request #274
Opened 2023-03-20 22:08 UTC by calebk1

Adding metadata to all the documents.

2023-03-21 23:52 UTC, swarna04 requested changes

2023-03-21 23:58 UTC, swarna04 commented
@calebk1 Thanks for the work here 👍 Should we also add relevant keywords to the different pages, maybe start with at least overview pages for different extensions? No hurry though!

2023-06-27 04:17 UTC, emdobrin commented
@calebk1 can you please refresh this PR and merge latest changes from main?
@swarna04 can we get this one merged?

2023-08-25 19:15 UTC, swarna04 commented on src/pages/documentation/mobile-core/lifecycle/api-reference.md
> +description: An API reference for the Mobile Core lifecycle extension.
This is not resolved ⏫

2023-08-25 19:15 UTC, swarna04 approved these changes

2023-08-25 19:36 UTC, merged