Added code-based experiences docs
AdobeDocs/aep-mobile-sdkdocs pull request #522
Opened 2024-03-09 03:10 UTC by swarna04

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-03-11 22:13 UTC, calebk1 requested changes
Content looks good, but a few header changes needs to be done.

2024-03-11 22:13 UTC, calebk1 commented on src/pages/edge/adobe-journey-optimizer/public-classes/tabs/surface.md
> +#### Syntax
Same comment again for H4s.

2024-03-18 20:41 UTC, spoorthipujariadobe commented on src/pages/edge/adobe-journey-optimizer/public-classes/proposition-item.md
> +### itemId
Moving it down an H level would hide it from the right navigation highlights which appears under "**ON THIS PAGE**"

2024-03-18 20:44 UTC, spoorthipujariadobe commented on src/pages/edge/adobe-journey-optimizer/public-classes/proposition-item.md
> +### itemId
I can add a line of content in between the two H2 if that helps?

2024-03-22 20:04 UTC, sbenedicadb commented
closing this pr and pulling in the changes in #539

2024-03-22 20:04 UTC, closed without merging